spring:
  application:
    name: Treasure Hunt

  datasource:
    url:  jdbc:mysql://localhost:3306/treasurehunt?useTimezone=true&serverTimezone=UTC
    username: root
    password:

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect


server:
  port: 8081
